### ISSUE TITLE
Not installing properly on regular computers (non-circuitpython devices)

### ISSUE THREAD

**Issue by duckythescientist** [adafruit/Adafruit_CircuitPython_Waveform#23] opened 2022-09-04 21:28 UTC
As far as I can tell, the actual Python files for this library aren't being installed anywhere on the system when doing a pip install. I've tried this on two separate Linux desktops and in a venv. I get an `adafruit_circuitpython_waveform-***.dist-info` folder in my `site-packages` but there's no corresponding `adafruit_waveform` folder with any source/pyc.

```
duck@alura:~/test$ mkdir project-name && cd project-name
duck@alura:~/test/project-name$ python3 -m venv .venv
duck@alura:~/test/project-name$ source .venv/bin/activate
[.venv]duck@alura:~/test/project-name$ pip3 install adafruit-circuitpython-waveform
Collecting adafruit-circuitpython-waveform
  Using cached adafruit_circuitpython_waveform-1.3.16-py3-none-any.whl (3.4 kB)
Installing collected packages: adafruit-circuitpython-waveform
Successfully installed adafruit-circuitpython-waveform-1.3.16
[.venv]duck@alura:~/test/project-name$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from adafruit_waveform import sine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'adafruit_waveform'
```

**Comment by tekktrik** [comment] 2022-09-05 00:42
Hi @duckythescientist, looks like the problem is in the `pyproject.toml` file, so the contents on PyPI won't install correctly.  PR #24 fixes this, but if you want the fix in the meantime, you can download the source code and make [this change](https://github.com/adafruit/Adafruit_CircuitPython_Waveform/pull/24/commits/f39f96870d98d716f1eb507390f575309bebedbd).  You can then use `pip install .` in the root repository folder to install the library.

Of course, once the PR is merged and uploaded to PyPI, you can use `pip install --upgrade adafruit-circuitpython-waveform` to update to the latest :)

**Closed as completed** 2022-09-06 21:47 UTC
Labels: bug

**Comment by tekktrik** [comment] 2022-09-07 02:32
@duckythescientist You're good to upgrade!
